"""Publish a Scene Layer Package (SLPK) to ArcGIS Online as a hosted scene layer.

Runs inside the ArcGIS Pro conda environment so the signed-in Pro user is reused:
  %LOCALAPPDATA%\\Programs\\ArcGIS\\Pro\\bin\\Python\\Scripts\\propy.bat scripts\\agol_publish_scene.py data\\ce\\_slpk\\dubaimarina.slpk

Options
  --title "..."        item title (default: "Najma - <slug> massing", derived from the file name)
  --tags  "a,b,c"      item tags (default: najma,digitalchemy)
  --replace            if an item with the same title already exists (owner only), delete the old
                       package + scene layer first; otherwise the script refuses to create duplicates
  --print-token        also print a short-lived portal token for the signed-in user (opt-in; useful for
                       opening the proof page with ?token=... without the sign-in dialog)

Both items (the .slpk package and the hosted scene layer) are left PRIVATE (owner only).
Sharing is a decision for the owner - nothing here calls item.share().
A sidecar <slpk>.agol.json is written next to the package with the item ids, service URL and fields.
"""
import argparse
import json
import os
import sys
import time


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("slpk")
    ap.add_argument("--title", default=None)
    ap.add_argument("--tags", default="najma,digitalchemy")
    ap.add_argument("--replace", action="store_true")
    ap.add_argument("--print-token", action="store_true")
    a = ap.parse_args()
    if not a.title:
        a.title = "Najma - %s massing" % os.path.splitext(os.path.basename(a.slpk))[0]

    slpk = os.path.abspath(a.slpk)
    if not os.path.isfile(slpk):
        sys.exit("not found: " + slpk)
    size_mb = os.path.getsize(slpk) / 1e6
    print(f"package: {slpk} ({size_mb:.1f} MB)")

    from arcgis.gis import GIS  # noqa: E402

    gis = GIS("pro")
    me = gis.users.me
    if me is None:
        sys.exit("GIS('pro') did not authenticate - sign in to ArcGIS Online inside ArcGIS Pro first")
    print(f"signed in as {me.username} @ {gis.url}")

    # duplicate guard (owner scope only)
    existing = [it for it in gis.content.search(f'title:"{a.title}" AND owner:{me.username}', max_items=20)
                if it.title == a.title]
    if existing:
        print("existing items with this title:", [(it.id, it.type) for it in existing])
        if not a.replace:
            sys.exit("refusing to create duplicates - rerun with --replace, or pick another --title")
        for it in existing:
            print("deleting", it.id, it.type)
            try:
                it.protect(enable=False)
            except Exception:
                pass
            it.delete()

    district = a.title.replace("Najma - ", "").replace(" massing", "").replace(" (proof)", "").strip() or "district"
    props = {"type": "Scene Package", "title": a.title, "tags": a.tags,
             "snippet": f"CityEngine massing for {district}, one feature per footprint; the shape name's "
                        "leading b<i> token is the footprint index (join key for the names register).",
             "description": "Generated by naj-market-pulse/scripts/ce_export_slpk.py from the district scene "
                            "(footprints + heights from the register), published by agol_publish_scene.py. "
                            "Private - owner only. Lane guide: data/board/SCENELAYER_LANE.md"}
    t0 = time.time()
    print("uploading package ...", flush=True)

    def _upload(path):
        try:  # arcgis >= 2.3 API
            return gis.content.folders.get().add(item_properties=props, file=path).result()
        except Exception as e:  # legacy path (or surface the real error)
            if "409" in str(e) or "CONT_0027" in str(e) or "already exists" in str(e):
                raise
            print("folders.add failed (%s) - falling back to content.add" % str(e)[:80])
            return gis.content.add(item_properties=props, data=path)

    # ArcGIS Online enforces unique FILE names per owner (error 409 / CONT_0027), independent of
    # the item title - so a re-export of the same district, or a proof item that uploaded
    # "<slug>.slpk" earlier, blocks a plain upload. Retry once from a timestamped copy; the
    # title is unchanged, only the stored filename differs.
    upload_tmp = None
    try:
        pkg = _upload(slpk)
    except Exception as e:
        msg = str(e)
        if not ("409" in msg or "CONT_0027" in msg or "already exists" in msg):
            raise
        import shutil
        stem, ext = os.path.splitext(os.path.basename(slpk))
        upload_tmp = os.path.join(os.path.dirname(slpk), f"{stem}_{time.strftime('%Y%m%d%H%M%S')}{ext}")
        shutil.copyfile(slpk, upload_tmp)
        print(f"filename '{os.path.basename(slpk)}' already exists in this account (409) - "
              f"retrying as {os.path.basename(upload_tmp)}", flush=True)
        try:
            pkg = _upload(upload_tmp)
        finally:
            try:
                os.remove(upload_tmp)
            except OSError:
                pass
    print(f"package item: {pkg.id}  ({time.time() - t0:.0f}s)")

    t0 = time.time()
    print("publishing hosted scene layer ...", flush=True)
    layer_item = pkg.publish()
    print(f"scene layer item: {layer_item.id}  ({time.time() - t0:.0f}s)")
    print("scene layer url :", layer_item.url)
    print("item page       :", f"{gis.url.rstrip('/')}/home/item.html?id={layer_item.id}")
    print("sharing         :", getattr(layer_item, "access", "?"), "(left as-is: owner only)")

    fields, layer0_url = [], None
    try:
        lyr = layer_item.layers[0]
        layer0_url = lyr.url
        p = lyr.properties
        fields = [(f["name"], f.get("type")) for f in p.get("fields", [])]
        print("layer 0        :", layer0_url)
        print("geometry type   :", p.get("layerType"), "/", p.get("geometryType"))
        print("fields          :", fields)
    except Exception as e:
        print("could not read layer properties yet (service still building?):", str(e)[:120])

    side = {
        "slpk": slpk, "title": a.title, "owner": me.username, "portal": gis.url,
        "package_item_id": pkg.id, "scene_layer_item_id": layer_item.id,
        "scene_layer_url": layer_item.url, "layer0_url": layer0_url,
        "item_page": f"{gis.url.rstrip('/')}/home/item.html?id={layer_item.id}",
        "access": getattr(layer_item, "access", None), "fields": fields,
        "published_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    with open(slpk + ".agol.json", "w", encoding="utf-8") as f:
        json.dump(side, f, indent=2)
    print("sidecar        :", slpk + ".agol.json")

    if a.print_token:
        try:
            print("token (short-lived, do not commit):", gis._con.token)
        except Exception as e:
            print("token:", e)


if __name__ == "__main__":
    main()
