"""Unit-type card sheets v4 - The Symphony by Imtiaz. A4 landscape PNG + PDF per type + combined PDF.

v4 (2 Sep 2026, Kendall-directed): NO imported drawings, NO SVG. Both images are rasterised from vector PDFs that Revit
exports from OUR model (revit_v2_cards.cs): the whole floor plate with this unit filled crimson (left), key facts (top right),
the unit's own 1:50 plan with room tags, areas and dimension strings (bottom right). Layout generated by revit_v2_emit.py
under the Neufert gate (corridor frontage, hall, no pass-through rooms, window per habitable room, door widths, room minimums).
Config: data/cards/card_config.json - vicinity: data/cards/vicinity.json - availability: newest developer sheet JSON -
room schedule: data/revit/v2_<floor>.json + Revit areas read back into data/revit/cards/areas.json (optional).
"""
import collections, glob, json, os, re, sys
import fitz  # PyMuPDF
from PIL import Image, ImageDraw, ImageFont

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
CARDS_DIR = os.path.join(ROOT, "data", "cards")
PDF_DIR = os.path.join(ROOT, "data", "revit", "cards")
ENG = r"C:\Users\kwils\OneDrive\Desktop\DigitAlchemy_31MAY2026\Client_Engagements\Imtiaz\02_Execution\04_Golden_Building_Symphony\02_Revit\unit_cards"
OUT = os.path.join(ENG, "sheets")
os.makedirs(OUT, exist_ok=True)
CFG = json.load(open(os.path.join(CARDS_DIR, "card_config.json"), encoding="utf-8-sig"))
TEAL, GOLD, INK, MUT, PAPER = (10, 79, 74), (197, 165, 106), (28, 32, 30), (110, 118, 114), (250, 249, 246)
HI = tuple(CFG.get("highlight_rgb", [196, 30, 58]))
W, H = 3508, 2480


def F(name, size):
    return ImageFont.truetype(r"C:\Windows\Fonts\%s.ttf" % name, size)


H1, H2, H3, B, SM, XS = F("georgia", 66), F("georgia", 40), F("georgia", 34), F("segoeui", 30), F("segoeui", 26), F("segoeui", 22)


def latest_avail(dev="imtiaz"):
    best = None
    for p in glob.glob(os.path.join(ROOT, "data", "avail", dev + "_*.json")):
        m = re.search(r"_(\d{4}-\d{2}-\d{2})(_auto)?\.json$", p)
        if m:
            rank = (m.group(1), 0 if m.group(2) else 1)
            if best is None or rank > best[0]:
                best = (rank, p)
    return best[1]


avail_path = latest_avail()
avail = json.load(open(avail_path, encoding="utf-8"))
sheet_date = avail.get("sheet_date", "")
by_type = collections.defaultdict(list)
for p in avail["projects"]:
    if "symphony" in p.get("p", "").lower():
        for u in p["units"]:
            by_type[u[1]].append(u)
vic = json.load(open(os.path.join(CARDS_DIR, "vicinity.json"))) if os.path.exists(os.path.join(CARDS_DIR, "vicinity.json")) else {}
areas = json.load(open(os.path.join(PDF_DIR, "areas.json"))) if os.path.exists(os.path.join(PDF_DIR, "areas.json")) else {}

# key, title, unit, floor, sheet type, floors text, view text
CARDS = [
    ("MasterSuite_1BR", "Master Suite - 1 Bedroom", "1101", "F11", "1 B/R", "Floors 10-22 - west wing and NW corner - 3 per floor", "West and north faces - Park / Community per the developer compass"),
    ("1BR", "1 Bedroom", "1907", "F19", "1 B/R", "Floors 10-33 - 5-7 per floor - unit 1907 is on the 28-Aug sheet", "East face - Community per the developer compass"),
    ("2BR", "2 Bedroom", "2902", "F29", "2 B/R", "Floors 10-33 - 3-4 per floor - unit 2902 is on the 28-Aug sheet", "North face - Burj Khalifa & Lagoon per the developer compass"),
    ("3BR", "3 Bedroom", "2410", "F24", "3 B/R", "Floors 24, 26, 28, 30 - 2 per floor - units 2410 and 2810 are on the 28-Aug sheet", "West wing - Park per the developer compass"),
    ("4BR", "4 Bedroom", "3201", "F32", "4 B/R", "Floor 32 - 2 units", "North-west wrap - three aspects"),
    ("4BR_Duplex_lower", "4 Bedroom Duplex - lower level (33rd)", "3307", "F33", "4 B/R Duplex", "Floors 33-34 - unit 3307 - private pool terrace", "West wing + NW corner - Skyline, Lagoon & Cityscape (developer claim)"),
    ("4BR_Duplex_upper", "4 Bedroom Duplex - upper level (34th)", "3407", "F34", "4 B/R Duplex", "Floors 33-34 - unit 3307 - planted upper terrace", "West wing + NW corner - Skyline, Lagoon & Cityscape (developer claim)"),
]
LEGEND = [("This unit on the plate", HI), ("Living / kitchen", (232, 219, 190)), ("Bedrooms + maid", (206, 217, 226)),
          ("Bath / ensuite / powder / maid WC", (222, 222, 222)), ("Hall", (228, 244, 240)), ("Balcony / terrace", (236, 220, 236))]


def raster(pdf, dpi=300):
    """PDF page -> PIL image cropped to the drawing (white margin trimmed)."""
    if not os.path.exists(pdf):
        return None
    pg = fitz.open(pdf)[0]
    pix = pg.get_pixmap(dpi=dpi)
    im = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
    g = im.convert("L").point(lambda v: 255 if v < 245 else 0)
    bb = g.getbbox()
    if bb:
        pad = 30
        im = im.crop((max(0, bb[0] - pad), max(0, bb[1] - pad), min(im.width, bb[2] + pad), min(im.height, bb[3] + pad)))
    return im


def fit(img, box_w, box_h):
    r = min(box_w / img.width, box_h / img.height)
    return img.resize((max(1, int(img.width * r)), max(1, int(img.height * r))), Image.LANCZOS)


def wrap(draw, text, font, width):
    words, lines, cur = text.split(), [], ""
    for w in words:
        t = (cur + " " + w).strip()
        if draw.textlength(t, font=font) <= width:
            cur = t
        else:
            lines.append(cur); cur = w
    if cur:
        lines.append(cur)
    return lines


def icon(d, kind, x, y, s=64):
    """Vector icon drawn straight into the sheet: teal disc, gold line art. kinds: metro, school, people, coin, mall, compass."""
    r = s // 2; cx, cy = x + r, y + r
    d.ellipse([x, y, x + s, y + s], fill=TEAL)
    g, w = GOLD, max(3, s // 20)
    if kind == "metro":                                         # train front: body, window band, lights, rails
        d.rounded_rectangle([cx - r * .48, cy - r * .55, cx + r * .48, cy + r * .40], radius=r * .18, outline=g, width=w)
        d.rounded_rectangle([cx - r * .34, cy - r * .40, cx + r * .34, cy - r * .05], radius=r * .06, fill=g)
        d.ellipse([cx - r * .36, cy + r * .10, cx - r * .18, cy + r * .28], fill=g); d.ellipse([cx + r * .18, cy + r * .10, cx + r * .36, cy + r * .28], fill=g)
        d.line([cx - r * .55, cy + r * .58, cx - r * .25, cy + r * .42], fill=g, width=w); d.line([cx + r * .55, cy + r * .58, cx + r * .25, cy + r * .42], fill=g, width=w)
    elif kind == "school":                                      # mortarboard + tassel
        d.polygon([(cx, cy - r * .45), (cx + r * .60, cy - r * .12), (cx, cy + r * .20), (cx - r * .60, cy - r * .12)], fill=g)
        d.line([cx - r * .34, cy + r * .02, cx - r * .34, cy + r * .32], fill=g, width=w); d.line([cx - r * .34, cy + r * .32, cx + r * .34, cy + r * .32], fill=g, width=w)
        d.line([cx + r * .60, cy - r * .12, cx + r * .60, cy + r * .30], fill=g, width=w); d.ellipse([cx + r * .52, cy + r * .28, cx + r * .68, cy + r * .44], fill=g)
    elif kind == "people":                                      # two figures
        for dx, k in ((-r * .26, 1.0), (r * .26, .85)):
            d.ellipse([cx + dx - r * .16 * k, cy - r * .48 * k, cx + dx + r * .16 * k, cy - r * .16 * k], fill=g)
            d.rounded_rectangle([cx + dx - r * .28 * k, cy - r * .10 * k, cx + dx + r * .28 * k, cy + r * .48 * k], radius=r * .16, fill=g)
    elif kind == "coin":                                        # coin with an upward arrow (purchasing power)
        d.ellipse([cx - r * .48, cy - r * .48, cx + r * .48, cy + r * .48], outline=g, width=w)
        d.line([cx, cy + r * .26, cx, cy - r * .22], fill=g, width=w + 1)
        d.polygon([(cx, cy - r * .34), (cx - r * .18, cy - r * .10), (cx + r * .18, cy - r * .10)], fill=g)
    elif kind == "mall":                                        # shopping bag
        d.rounded_rectangle([cx - r * .42, cy - r * .20, cx + r * .42, cy + r * .48], radius=r * .08, outline=g, width=w)
        d.arc([cx - r * .26, cy - r * .55, cx + r * .26, cy + r * .05], 180, 360, fill=g, width=w)
    elif kind == "compass":
        d.ellipse([cx - r * .5, cy - r * .5, cx + r * .5, cy + r * .5], outline=g, width=w)
        d.polygon([(cx, cy - r * .42), (cx - r * .12, cy), (cx + r * .12, cy)], fill=g); d.polygon([(cx, cy + r * .42), (cx - r * .12, cy), (cx + r * .12, cy)], fill=(255, 255, 255))


def unit_rooms(unit, floor):
    j = json.load(open(os.path.join(ROOT, "data", "revit", "v2_%s.json" % floor)))
    u = next(x for x in j["units"] if x["unit"] == unit)
    rows = [r for r in j["rooms"] if r[3].startswith(unit + "-")]
    return u, rows


pages = []
for key, title, unit, floor, sheet_type, floors, view in CARDS:
    im = Image.new("RGB", (W, H), PAPER)
    d = ImageDraw.Draw(im)
    # header
    d.rectangle([0, 0, W, 290], fill=TEAL); d.rectangle([0, 290, W, 302], fill=GOLD)
    d.text((120, 58), CFG["building"], font=H1, fill=(255, 255, 255))
    d.text((120, 160), CFG["location"] + "   |   Unit type card   |   " + title + "   |   Unit " + unit, font=B, fill=(220, 228, 226))
    cur = "Curated by " + CFG["curated_by"] + " for " + CFG["curated_for"]
    d.text((W - 120 - d.textlength(cur, font=B), 72), cur, font=B, fill=GOLD)
    av = "Availability as of " + sheet_date
    d.text((W - 120 - d.textlength(av, font=SM), 124), av, font=SM, fill=(220, 228, 226))
    d.text((W - 120 - d.textlength(title, font=H2), 184), title, font=H2, fill=GOLD)

    # LEFT: floor plate from Revit (vector PDF -> 300 dpi), this unit crimson
    px, py = 120, 360
    plate = raster(os.path.join(PDF_DIR, "floor_%s.pdf" % key))
    if plate is not None:
        plate = fit(plate, 1880, 1480)
        d.rectangle([px - 12, py - 12, px + plate.width + 12, py + plate.height + 12], outline=(215, 212, 205), width=3)
        im.paste(plate, (px, py))
        ph = plate.height
    else:
        d.text((px, py), "floor plate export missing", font=B, fill=HI); ph = 100
    d.text((px, py + ph + 22), "Floor %s plate - DigitAlchemy Revit model (generator v2, Neufert-gated) - crimson = unit %s - project north up." % (floor[1:], unit), font=XS, fill=MUT)
    # vicinity under the plate
    vy = py + ph + 66
    d.text((px, vy), "Vicinity", font=H3, fill=TEAL); vy += 50
    metro = (vic.get("metro") or [])[:2]
    schools = [s for s in (vic.get("schools") or []) if "tennis" not in (s.get("name") or "").lower()][:3]
    demo = {r.get("radius_km"): r for r in (vic.get("demographics") or [])}
    malls = (vic.get("malls") or [])[:2]
    rows = []                                                   # (icon kind, bold lead, text)
    if metro:
        rows.append(("metro", "Metro", " - ".join("%s %.1f km" % (m["name"].replace(" Metro Station", ""), m["km"]) for m in metro) + " (straight-line)"))
    if schools:
        rows.append(("school", "Schools", " - ".join("%s %.1f km" % (s["name"], s["km"]) for s in schools)))
    if 1 in demo:
        r1 = demo[1]; r3 = demo.get(3, {})
        rows.append(("people", "Who lives here", "%s residents, %s households within 1 km%s" % (
            format(int(r1["pop"]), ","), format(int(r1["households"]), ","), ("; %s residents within 3 km" % format(int(r3["pop"]), ",")) if r3 else "")))
        rows.append(("coin", "Purchasing power", "index %s within 1 km (UAE = 100)%s - Esri 2024" % (r1["pp_index"], ("; %s within 3 km" % r3["pp_index"]) if r3 else "")))
    if malls:
        rows.append(("mall", "Malls", " - ".join("%s %.1f km" % (m["name"], m["km"]) for m in malls)))
    for kind, lead, txt in rows:
        icon(d, kind, px, vy - 6, 60)
        lead_w = d.textlength(lead + "  ", font=B)
        d.text((px + 80, vy), lead, font=B, fill=TEAL)
        segs = wrap(d, txt, SM, 1880 - 80 - lead_w)
        d.text((px + 80 + lead_w, vy + 4), segs[0] if segs else "", font=SM, fill=INK)
        for seg in segs[1:]:
            vy += 34; d.text((px + 80 + lead_w, vy + 4), seg, font=SM, fill=INK)
        vy += 66

    # RIGHT TOP: key facts
    x, y = 2120, 360
    d.text((x, y), "Key facts - unit " + unit, font=H2, fill=TEAL); y += 62
    u, rl = unit_rooms(unit, floor)
    su = by_type.get(sheet_type, [])
    if su:
        avail_line = "Developer sheet %s: %d unit(s) of this type available - from AED %s - %s-%s sq ft - units %s" % (
            sheet_date, len(su), format(int(min(q[3] for q in su)), ","), format(int(min(q[2] for q in su)), ","),
            format(int(max(q[2] for q in su)), ","), ", ".join(str(q[0]) for q in su[:8]) + (" ..." if len(su) > 8 else ""))
    else:
        avail_line = "Developer sheet %s: none of this type listed as available" % sheet_date
    a_int = sum(areas.get(r[3], 0) for r in rl if r[5] not in ("balcony", "corridor")) if areas else None
    a_bal = sum(areas.get(r[3], 0) for r in rl if r[5] == "balcony") if areas else 0
    prog = u.get("programme", {})
    prog_line = "Programme: %d bedroom(s)%s - %d bathroom(s) incl. %d ensuite(s)%s%s" % (prog.get("bedrooms", 0), " + maid's room" if prog.get("maid") else "", prog.get("bathrooms", 0), prog.get("ensuites", 0), " + guest powder room" if prog.get("powder") else "", " - maid WC" if prog.get("maid") else "")
    bullets = [floors, view, avail_line, prog_line,
               "Bay %.1f x %.1f m (facade x depth)%s - layout: DigitAlchemy generator v2 under the Neufert gate; indicative, not surveyed" % (
                   u["width_mm"] / 1000, u["depth_mm"] / 1000, (" - ~%d m2 interior + %d m2 balcony/terrace = ~%s sq ft" % (round(a_int), round(a_bal), format(round((a_int + a_bal) * 10.764), ","))) if a_int else ""),
               "Every room classified: Uniclass 2015 SL - OmniClass T11 - Brick - Haystack"]
    for btxt in bullets:
        for i, line in enumerate(wrap(d, btxt, SM, 1260)):
            d.text((x + (0 if i == 0 else 30), y), ("-  " if i == 0 else "") + line, font=SM, fill=INK); y += 33
        y += 6
    # room schedule: inside dimensions (from the generator rectangles) + Revit areas, two columns
    y += 6
    d.text((x, y), "Rooms - inside dimensions and areas", font=H3, fill=TEAL); y += 48
    sched = [r for r in rl if r[5] != "corridor"]
    col_w, rows_per_col = 640, 7
    for i, r in enumerate(sched):
        cx = x + (i // rows_per_col) * col_w; cy = y + (i % rows_per_col) * 32
        if cx + col_w > W - 80:
            break
        a = areas.get(r[3]); rc = r[7]
        dims_txt = "%.1f x %.1f m" % ((rc[2] - rc[0]) / 1000, (rc[3] - rc[1]) / 1000)
        d.text((cx, cy), r[3], font=XS, fill=MUT); d.text((cx + 110, cy), "%s  %s%s" % (r[2].replace(" + entrance", ""), dims_txt, ("  %.0f m2" % a) if a else ""), font=XS, fill=INK)
    y += min(len(sched), rows_per_col) * 32 + 12

    # RIGHT BOTTOM: unit plan from Revit (1:50, tags + dims)
    up = raster(os.path.join(PDF_DIR, "unit_%s.pdf" % key))
    box_top = y + 6; box_h = H - 240 - box_top - 150   # unit plan takes the rest of the column (mobile: this is what gets zoomed)
    if up is not None:
        up = fit(up, 1300, box_h)
        ux = x + (1300 - up.width) // 2
        d.rectangle([ux - 10, box_top - 10, ux + up.width + 10, box_top + up.height + 10], outline=(215, 212, 205), width=3)
        im.paste(up, (ux, box_top))
        d.text((x, box_top + up.height + 18), "Unit %s - 1:50 plan from the DigitAlchemy model: room names + areas, overall dimensions (mm), door swings, balcony." % unit, font=XS, fill=MUT)
    else:
        d.text((x, box_top), "unit plan export missing", font=B, fill=HI)
    # legend (two rows, readable on a phone)
    ly = H - 240 - 96; lx = x
    for i, (name, col) in enumerate(LEGEND):
        if i == 3:
            ly += 44; lx = x
        d.rectangle([lx, ly + 6, lx + 36, ly + 34], fill=col, outline=(120, 120, 120)); d.text((lx + 48, ly + 2), name, font=SM, fill=INK)
        lx += 48 + int(d.textlength(name, font=SM)) + 44

    # footer
    d.rectangle([0, H - 210, W, H], fill=(240, 238, 232)); d.rectangle([0, H - 210, W, H - 204], fill=GOLD)
    yy = H - 190
    for line in wrap(d, CFG["confidentiality"], XS, W - 240):
        d.text((120, yy), line, font=XS, fill=MUT); yy += 30
    d.text((120, H - 62), CFG["contact"], font=SM, fill=TEAL)
    src_line = "Sources: DigitAlchemy Revit model (generator v2) - developer availability sheet " + sheet_date + " - Esri World Geocoding & GeoEnrichment (2024) - Imtiaz floor-plan deck (census)"
    d.text((W - 120 - d.textlength(src_line, font=XS), H - 56), src_line, font=XS, fill=MUT)

    out_png = os.path.join(OUT, "sheet_%s.png" % key)
    im.save(out_png, optimize=True); im.save(out_png[:-4] + ".pdf", resolution=300); pages.append(im)
    print("sheet", key)

if pages:
    pages[0].save(os.path.join(OUT, "TheSymphony_UnitTypeCards.pdf"), save_all=True, append_images=pages[1:], resolution=300)
    print("combined PDF:", len(pages), "pages ->", OUT)
