"""Build districts with CityEngine 2026.1, unattended - one fresh CityEngine process per district (Kendall, 30 Sep 2026).

Why: the 2025.1 lane drives one long-lived CityEngine over a py4j bridge. Memory grows across districts (83 MB -> 13 GB)
and the bridge dies, so a restart needs a person. 2026.1 runs a startup script and exits by itself, so each district gets
a clean process and nothing can accumulate or hang between them.

What it runs: the PRODUCTION build, ce_batch_v2.py, as a lab copy (C:\\Dev\\ce2026_lab\\ce2026_batch.py, generated by
make_lab_copy.py) whose only differences are paths. It works in the lab workspace C:\\Dev\\ce2026_lab and NEVER opens the
production workspace, because 2026.1 can upgrade 2025.1 projects there.

Per district:
  1. copy data/ce/<slug> inputs and the production scene /najma/scenes/<slug>.cej into the lab (fresh every run)
  2. launch CityEngine 2026.1 with -DpythonStartupScript=run_lab.py for that slug; wait for the process to exit
  3. compare the lab GLB with the production one, building by building (triangles, names, materials, images)

Outputs stay in the lab (C:\\Dev\\ce2026_lab\\data_ce). Nothing here writes a production file or publishes anything.
Parity is recorded in logs/ce2026_parity_<date>.json.

  python scripts/ce2026_run.py bukadra businessbay         textured (v3) build
  python scripts/ce2026_run.py --timeout 3600 liwan1
"""
import glob
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
LAB = r"C:\Dev\ce2026_lab"
CE_EXE = r"C:\Program Files\ArcGIS\CityEngine2026.1\CityEngine.exe"
PROD_WS = r"C:\Users\kwils\OneDrive\Documents\CityEngine\Default Workspace\najma"
VENV = os.path.join(LAB, "venv311")
INPUTS = ("buildings.geojson", "facade_v2.json", "heights_register.json", "facade_match.json")


def log(*a):
    print(time.strftime("%H:%M:%S"), *a, flush=True)


def stage(slug):
    """Fresh copies of this district's inputs and production scene into the lab."""
    src = os.path.join(ROOT, "data", "ce", slug)
    dst = os.path.join(LAB, "data_ce", slug)
    os.makedirs(dst, exist_ok=True)
    for f in INPUTS:
        if os.path.exists(os.path.join(src, f)):
            shutil.copy2(os.path.join(src, f), os.path.join(dst, f))
    scene = os.path.join(PROD_WS, "scenes", slug + ".cej")
    if not os.path.exists(scene):
        raise FileNotFoundError("no production scene " + scene)
    shutil.copy2(scene, os.path.join(LAB, "najma", "scenes", slug + ".cej"))
    for f in glob.glob(os.path.join(LAB, "data_ce", "_glb", "sky_%s_v3*" % slug)):
        os.remove(f)                                     # never compare against a previous lab run
    lock = os.path.join(LAB, "data_ce", ".ce_lock")
    if os.path.exists(lock):
        os.remove(lock)                                  # the lab lock belongs to this runner alone


def ce2026_running():
    """PIDs of CityEngine 2026.1 processes (2025.1 is ignored - it is a different install and workspace)."""
    r = subprocess.run(["powershell", "-NoProfile", "-Command",
                        "Get-Process CityEngine -EA SilentlyContinue | Where-Object { $_.Path -like '*CityEngine2026*' } | "
                        "ForEach-Object { '' + $_.Id + '|' + $_.MainWindowTitle }"], capture_output=True, text=True)
    return [l.strip() for l in r.stdout.splitlines() if l.strip()]


def build(slug, timeout):
    busy = ce2026_running()
    if busy:
        # a second CityEngine cannot open a workspace the first still holds; it would exit at once and every later
        # district would "fail" in seconds (30 Sep: one hang turned into three failures this way)
        return {"ok": False, "error": "CityEngine 2026.1 already running (%s) - not launching" % "; ".join(busy), "blocked": True}
    res = os.path.join(LAB, "out", "run_lab.json")
    if os.path.exists(res):
        os.remove(res)
    env = dict(os.environ, CE2026_SLUG=slug)
    t = time.time()
    p = subprocess.Popen([CE_EXE, "-data", LAB, "-vmargs",
                          "-DpythonStartupScript=" + os.path.join(LAB, "run_lab.py"),
                          "-DpythonStartupEnvironment=" + VENV], env=env)
    try:
        p.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        title = "; ".join(ce2026_running())
        return {"ok": False, "blocked": True, "error": "timeout after %ds - CityEngine left running for inspection (%s)" % (timeout, title or p.pid)}
    r = json.load(open(res, encoding="utf-8")) if os.path.exists(res) else {"ok": False, "error": "no run_lab.json"}
    r["wall_s"] = round(time.time() - t, 1)
    return r


def glb_stats(p):
    b = open(p, "rb").read()
    n = struct.unpack("<I", b[12:16])[0]
    j = json.loads(b[20:20 + n])
    per = {}
    for me in j["meshes"]:
        m = re.match(r"b(\d+)", me.get("name") or "")
        if not m:
            continue
        t = 0
        for pr in me["primitives"]:
            a = j["accessors"][pr["indices"]] if "indices" in pr else j["accessors"][pr["attributes"]["POSITION"]]
            t += a["count"] // 3
        per[int(m.group(1))] = per.get(int(m.group(1)), 0) + t
    return {"per": per, "names": sorted(me.get("name") or "" for me in j["meshes"]),
            "materials": len(j.get("materials", [])), "images": len(j.get("images", [])), "bytes": len(b)}


def parity(slug):
    new_p = os.path.join(LAB, "data_ce", "_glb", "sky_%s_v3_0.glb" % slug)
    old_p = os.path.join(ROOT, "data", "ce", "_glb", "sky_%s_v3_0.merged.glb" % slug)
    if not os.path.exists(new_p):
        return {"parity": False, "why": "no lab GLB"}
    if not os.path.exists(old_p):
        return {"parity": None, "why": "no production merged GLB to compare with"}
    n, o = glb_stats(new_p), glb_stats(old_p)
    diff = [k for k in set(n["per"]) | set(o["per"]) if n["per"].get(k) != o["per"].get(k)]
    same = not diff and n["names"] == o["names"] and n["materials"] == o["materials"] and n["images"] == o["images"]
    return {"parity": same, "buildings": [len(n["per"]), len(o["per"])],
            "triangles": [sum(n["per"].values()), sum(o["per"].values())],
            "buildings_differing": len(diff), "differing_sample": sorted(diff)[:10],
            "names_equal": n["names"] == o["names"], "materials": [n["materials"], o["materials"]],
            "images": [n["images"], o["images"]], "bytes": [n["bytes"], o["bytes"]]}


def main():
    args = sys.argv[1:]
    timeout = 3600
    if "--timeout" in args:
        i = args.index("--timeout"); timeout = int(args[i + 1]); del args[i:i + 2]
    slugs = [a for a in args if not a.startswith("--")]
    subprocess.run([sys.executable, os.path.join(LAB, "make_lab_copy.py")], check=True)   # lab copy tracks production
    out = {"started": time.strftime("%Y-%m-%dT%H:%M:%S"), "ce": CE_EXE, "districts": {}}
    path = os.path.join(ROOT, "logs", "ce2026_parity_%s.json" % time.strftime("%Y%m%d_%H%M"))
    for slug in slugs:
        log("=== %s" % slug)
        try:
            stage(slug)
            r = build(slug, timeout)
            r.update(parity(slug) if r.get("ok") else {"parity": False})
        except Exception as e:
            r = {"ok": False, "error": repr(e)[:300], "parity": False}
        out["districts"][slug] = r
        log("  %s  ok=%s parity=%s  %s  buildings %s  triangles %s  (%ss)" % (
            slug, r.get("ok"), r.get("parity"), r.get("error", "") or "", r.get("buildings"), r.get("triangles"), r.get("wall_s")))
        json.dump(out, open(path, "w", encoding="utf-8"), indent=1)
        if r.get("blocked"):
            log("  STOPPING the batch: CityEngine 2026.1 is still open (a dialog such as 'License validation failed' "
                "blocks its exit). Close it, then re-run the remaining districts.")
            break
    good = [s for s, r in out["districts"].items() if r.get("parity")]
    log("=== %d of %d built with exact parity: %s" % (len(good), len(slugs), " ".join(good) or "none"))
    log("report: " + os.path.relpath(path, ROOT))
    return 0 if len(good) == len(slugs) else 1


if __name__ == "__main__":
    sys.exit(main())
