"""LAB (context / scenery, research only): generate lab_context.cga FROM THE PALETTE, compile it with CityEngine
2026.1's HEADLESS CGA compiler, pack a rule package PyPRT (and CityEngine) can run.

The rule is written by this script, never by hand: every colour, roughness, metallic, stack height and texture tile in
it is read from data/lab/context/<slug>/context_palette.json, and every species' asset / target size from the same
file + assets/assets.json. Change the palette -> re-run -> CityEngine, its Datasmith export and the web GLB all move.

Compiler: C:/Program Files/ArcGIS/CityEngine2026.1/CityEngine.exe -application com.esri.cgac.application (no GUI, no
bridge, no scene), in a THROW-AWAY Eclipse workspace + project under C:/Dev/ce2026_lab/cgac_ctx_<time>/ that is deleted
afterwards. Never -data C:/Dev/ce2026_lab, never the CE Python API, never a .ce_lock (the 24-district batch owns those).
The rule references only its own assets (/lab_context/assets/...), so no ESRI.lib link is needed at all.
Packing as scripts/lab_ghosts_rpk.py: bytecode bin/, source rules/, assets, .resolvemap.xml, 7z LZMA non-solid.
PyPRT 1.12 (PRT 3.3, CGAC 2.10) loads the 2026.1 bytecode (CGAC 2.11) with a "potentially unsupported" warning -
checked on a probe rule before this was written, and re-checked on every build (verify step).

  python scripts/lab_context_rpk.py [businessbay]   -> data/lab/context/<slug>/rules/lab_context.cga, lab_context.rpk, rpk_info.json
"""
import glob
import json
import os
import shutil
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lab_context_common as C

SLUG = (sys.argv[1:] or ["businessbay"])[0]
OUT = C.lab_dir(SLUG)
NAME = "lab_context"
CITYENGINE = r"C:\Program Files\ArcGIS\CityEngine2026.1\CityEngine.exe"
SEVENZIP = r"C:\Program Files\7-Zip\7z.exe"
WORK_ROOT = r"C:\Dev\ce2026_lab"

# species -> (asset stem, size axis h | len | native, pivot, topper). pivot "origin": the asset origin (trunk base / crane
# mast) lands on the point (Esri Plant_Loader, ue_sobha_foliage); "centre": bbox centred in x/z, base on the ground
# (ue_bb_v0_build.scatter). topper = (plant stem, plant height m) set on top of the object (L_BB_v1 planter: hedge at +55 cm)
SPECIES = {
    "date_palm": ("PhoenixDactylifera", "h", "origin", None), "washingtonia": ("WashingtoniaFilifera", "h", "origin", None),
    "acacia": ("AcaciaTortilis", "h", "origin", None), "ficus": ("FicusBenjamina", "h", "origin", None),
    "parkinsonia": ("ParkinsoniaAculeata", "h", "origin", None), "buxus": ("BuxusSempervirens", "h", "origin", None),
    "lamp": ("lamp_v1", "h", "centre", None), "bench": ("bench", "len", "centre", None), "bin": ("bin", "h", "centre", None),
    "bus_shelter": ("bus_shelter", "h", "centre", None), "bollard": ("bollard", "h", "centre", None),
    "planter": ("planter_v1", "h", "centre", ("BuxusSempervirens", 1.3 * 0.8)),
    "cafe_table": ("cafe_table", "h", "centre", None), "cafe_chair": ("cafe_chair", "h", "centre", None),
    "umbrella": ("umbrella", "h", "centre", None), "pot": ("pot", "h", "centre", ("BuxusSempervirens", 0.65)),
    "crane": ("tower_crane", "h", "origin", None),
    "site_0": ("site_0", "native", "centre", None), "site_1": ("site_1", "native", "centre", None), "site_2": ("site_2", "native", "centre", None),
    "site_3": ("site_3", "native", "centre", None), "site_4": ("site_4", "native", "centre", None),
    "car_0": ("car_0", "len", "centre", None), "car_1": ("car_1", "len", "centre", None), "car_2": ("car_2", "len", "centre", None),
    "car_3": ("car_3", "len", "centre", None), "car_4": ("car_4", "len", "centre", None),
}
CARS = []


def f(v):
    return ("%.4f" % v).rstrip("0").rstrip(".") if isinstance(v, float) else str(v)


def table(fn, pairs, default):
    lines = ["%s(r) =" % fn]
    for k, v in pairs:
        lines.append("\tcase r == \"%s\" : %s" % (k, v))
    lines.append("\telse : %s" % default)
    return "\n".join(lines)


def make_rule(pal):
    roles = {k[4:]: v for k, v in pal["roles"].items() if v["kind"] == "ground"}
    sp = pal["species"]
    tkey = lambda s: "car" if s.startswith("car_") else ("site_kit" if s.startswith("site_") else s)
    tgt = lambda s: sp[tkey(s)].get("target_h_m") or sp[tkey(s)].get("target_len_m")
    asset = lambda stem: "/%s/assets/%s.glb" % (NAME, stem)
    head = """/**
 * lab_context.cga - GENERATED by scripts/lab_context_rpk.py from data/lab/context/%(slug)s/context_palette.json
 * (%(built)s). Do not edit by hand: change the palette and re-run. Research use only.
 *
 * One rule for the scenery of a district, run the same way by PyPRT (web GLB) and by CityEngine (scene / Datasmith):
 *   kind "ground"    flat polygons with attr role -> material "ctx_<role>" (palette colour, roughness, metallic,
 *                    Unreal's two-tone noise baked into a world-projected tile), lifted to the role's stack height
 *                    above land level (Unreal L_BB_v1's heights; the land sits 1.20 m above the sand plane)
 *   kind "instance"  multi-face shapes, one small square per object: edge 0 = heading, side = scale jitter.
 *                    attr species picks the asset and its Unreal target size (ue_sobha_foliage / KITS).
 * Colours are sRGB here (CGA color() is sRGB; the palette holds linear and its sRGB hex).
 */
version "2024.0"

@Enum("ground","instance")
attr kind = "ground"
@Enum(%(roles_enum)s)
attr role = "asphalt"
@Enum(%(species_enum)s)
attr species = "date_palm"
@Description("baked noise tiles (Unreal's two-tone recipe); off = the flat palette colour")
attr Textured = true

@StartRule
Scenery -->
	case kind == "ground" : Ground
	else                  : Instances
""" % {"slug": SLUG, "built": time.strftime("%Y-%m-%d %H:%M"), "roles_enum": ",".join('"%s"' % r for r in roles),
       "species_enum": ",".join('"%s"' % s for s in list(SPECIES) + CARS)}
    tabs = [
        "# ---------------------------------------------------------------- palette (generated)",
        table("roleHex", [(r, '"%s"' % v["hex_srgb"]) for r, v in roles.items()], '"#808080"'),
        table("roleRough", [(r, f(float(v["roughness"]))) for r, v in roles.items()], "0.9"),
        table("roleMetal", [(r, f(float(v["metallic"]))) for r, v in roles.items()], "0"),
        table("roleOpacity", [(r, f(float(v["opacity"]))) for r, v in roles.items() if v.get("opacity") is not None], "1"),
        table("roleY", [(r, f(float(v["y_m"])) if v["y_m"] is not None else "-999") for r, v in roles.items()], "0"),
        table("roleTex", [(r, '"/%s/assets/%s"' % (NAME, v["texture"])) for r, v in roles.items() if v.get("texture")], '""'),
        table("roleTile", [(r, f(float(v["tile_m"]))) for r, v in roles.items() if v.get("tile_m")], "40"),
    ]
    ground = """
# ---------------------------------------------------------------- ground
Ground -->
	set(material.name, "ctx_" + role)
	set(material.roughness, roleRough(role))
	set(material.metallic, roleMetal(role))
	set(material.opacity, roleOpacity(role))
	GroundLift

GroundLift -->
	case roleY(role) > -900 :
		translate(rel, world, 0, roleY(role), 0)
		GroundPaint
	else :
		GroundPaint

GroundPaint -->
	case Textured && roleTex(role) != "" :
		color("#ffffff")
		set(material.colormap, roleTex(role))
		setupProjection(0, world.xz, roleTile(role), roleTile(role))
		projectUV(0)
		GroundSurface.
	else :
		color(roleHex(role))
		GroundSurface.
"""
    lines = ["", "# ---------------------------------------------------------------- dressing (targets from the palette's species table)",
             "Instances -->", "\tcomp(f) { all : Inst }", "",
             "Inst -->", "\talignScopeToGeometry(yUp, 0, 0)", "\tObj(scope.sx)", "",
             "Obj(k) -->"]
    for s, (stem, axis, pivot, top) in SPECIES.items():
        if top:
            lines.append('\tcase species == "%s" : Topped("%s", %s, "%s", %s, k)' % (s, asset(stem), f(float(tgt(s))), asset(top[0]), f(float(top[1]))))
        elif axis == "native":
            lines.append('\tcase species == "%s" : PlaceNative("%s", k)' % (s, asset(stem)))
        else:
            lines.append('\tcase species == "%s" : %s("%s", %s, k)' % (s, "PlaceOrigin" if pivot == "origin" else ("PlaceLen" if axis == "len" else "PlaceCentre"),
                                                                      asset(stem), f(float(tgt(s)))))
    lines.append("\telse : NIL")
    lines += ["",
              "# the asset origin (trunk base) on the square's centre, uniform scale to the target height",
              "PlaceOrigin(a, h, k) -->",
              "\ts(0, 0, 0) center(xz)",
              "\tPut(a, h * k / assetInfo(a, \"sy\"))", "",
              "Put(a, u) -->",
              "\tt(u * assetInfo(a, \"tx\"), u * assetInfo(a, \"ty\"), u * assetInfo(a, \"tz\"))",
              "\ts(u * assetInfo(a, \"sx\"), u * assetInfo(a, \"sy\"), u * assetInfo(a, \"sz\"))",
              "\ti(a)",
              "\tDressing.", "",
              "# bbox centred on the square's centre, base on the ground (Unreal's scatter): target = height",
              "PlaceCentre(a, h, k) -->",
              "\ts(0, 0, 0) center(xz)",
              "\tPutC(a, h * k / assetInfo(a, \"sy\"))", "",
              "# ... target = length along the heading (the asset's long axis is +x)",
              "PlaceLen(a, l, k) -->",
              "\ts(0, 0, 0) center(xz)",
              "\tPutC(a, l * k / assetInfo(a, \"sx\"))", "",
              "PutC(a, u) -->",
              "\tt(-u * assetInfo(a, \"sx\") / 2, 0, -u * assetInfo(a, \"sz\") / 2)",
              "\ts(u * assetInfo(a, \"sx\"), u * assetInfo(a, \"sy\"), u * assetInfo(a, \"sz\"))",
              "\ti(a)",
              "\tDressing.", "",
              "# real-size assets (Esri site kit): scale = the jitter only",
              "PlaceNative(a, k) -->",
              "\ts(0, 0, 0) center(xz)",
              "\tPutC(a, k)", "",
              "# an object with a plant on top (L_BB_v1 planter: box + hedge plant at +55 cm, 0.8 x 1.3 m; cafe pot + shrub)",
              "Topped(a, h, b, hb, k) -->",
              "\ts(0, 0, 0) center(xz)",
              "\t[ PutC(a, h * k / assetInfo(a, \"sy\")) ]",
              "\tt(0, h * k, 0)",
              "\tPut(b, hb * k / assetInfo(b, \"sy\"))", ""]
    return head + "\n" + "\n\n".join(tabs) + "\n" + ground + "\n".join(lines) + "\n"


def embedded_images(path, rel):
    """PRT's glTF decoder resolves a GLB's embedded image i through the resolve map: key '<asset>/img<i>', value
    'gltf:<asset>!/<byte offset in the file>/<byte length>/<name>' - the form CityEngine's own RPK export writes
    (see data/lab/instances/lab_instances.rpk). Without it the material is dropped (checked: 'failed to read material')."""
    g = C.GLB(path)
    import struct
    jl = struct.unpack("<I", open(path, "rb").read()[12:16])[0]
    bin0 = 20 + jl + 8
    out = []
    for i, im in enumerate(g.js.get("images", [])):
        bv = g.js["bufferViews"][im["bufferView"]]
        ext = "jpg" if im.get("mimeType") == "image/jpeg" else "png"
        stem = os.path.splitext(os.path.basename(rel))[0]
        out.append('  <entry key="/%s/%s/img%d" value="gltf:%s!/%d/%d/%s_%d.%s" />' % (NAME, rel, i, rel, bin0 + bv.get("byteOffset", 0), bv["byteLength"], stem, i, ext))
    return out


def compile_and_pack(pal, rule_text):
    stamp = time.strftime("%Y%m%d_%H%M%S")
    work = os.path.join(WORK_ROOT, "cgac_ctx_%s" % stamp)
    prj = os.path.join(work, NAME)
    os.makedirs(os.path.join(prj, "rules")); os.makedirs(os.path.join(work, "ws")); os.makedirs(os.path.join(work, "cgb"))
    cga = os.path.join(prj, "rules", NAME + ".cga")
    open(cga, "w", encoding="utf-8").write(rule_text)
    # assets into the throw-away project so the compiler sees /lab_context/assets/... (they are packed from the lab folder)
    shutil.copytree(os.path.join(OUT, "assets"), os.path.join(prj, "assets"))
    shutil.copytree(os.path.join(OUT, "textures"), os.path.join(prj, "assets", "textures"))
    cmd = [CITYENGINE, "-application", "com.esri.cgac.application", "-nosplash", "-consoleLog", "-data", os.path.join(work, "ws"),
           "-prj", prj, "-out", os.path.join(work, "cgb"), cga]
    t = time.time()
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    body = (r.stdout or "") + (r.stderr or "")
    errs = [l for l in body.splitlines() if " - ERROR" in l]
    warns = [l.strip() for l in body.splitlines() if " - WARNING" in l]
    cgbs = glob.glob(os.path.join(work, "cgb", "**", "*.cgb"), recursive=True)
    if errs or not cgbs:
        print(body[-3000:])
        sys.exit("compile failed: %d error(s), %d cgb - workspace kept for inspection: %s" % (len(errs), len(cgbs), work))
    took = time.time() - t
    stage = os.path.join(work, "stage")
    os.makedirs(os.path.join(stage, "rules")); os.makedirs(os.path.join(stage, "bin"))
    shutil.copy2(cga, os.path.join(stage, "rules", NAME + ".cga"))
    shutil.copy2(cgbs[0], os.path.join(stage, "bin", NAME + ".cgb"))
    shutil.copytree(os.path.join(prj, "assets"), os.path.join(stage, "assets"))
    entries = ['  <entry key="/%s/rules/%s.cga" value="rules/%s.cga" />' % (NAME, NAME, NAME),
               '  <entry key="rules/%s.cga" value="rules/%s.cga" />' % (NAME, NAME),
               '  <entry key="bin/%s.cgb" value="bin/%s.cgb" />' % (NAME, NAME)]
    for rt, _d, fs in os.walk(os.path.join(stage, "assets")):
        for fn in sorted(fs):
            rel = os.path.relpath(os.path.join(rt, fn), stage).replace("\\", "/")
            entries.append('  <entry key="/%s/%s" value="%s" />' % (NAME, rel, rel))
            if fn.endswith(".glb"):
                entries += embedded_images(os.path.join(rt, fn), rel)
    open(os.path.join(stage, ".resolvemap.xml"), "w", encoding="utf-8").write(
        '<?xml version="1.0" encoding="UTF-8"?>\n<resolvemap>\n' + "\n".join(entries) + "\n</resolvemap>\n")
    rpk = os.path.join(OUT, NAME + ".rpk")
    if os.path.exists(rpk):
        os.remove(rpk)
    z = subprocess.run([SEVENZIP, "a", "-t7z", rpk, "-m0=lzma", "-md=4m", "-ms=off", ".resolvemap.xml", "rules", "bin", "assets"],
                       cwd=stage, capture_output=True, text=True, timeout=300)
    if z.returncode != 0:
        print(z.stdout[-800:]); sys.exit("7z failed (%d); workspace kept: %s" % (z.returncode, work))
    shutil.rmtree(work, ignore_errors=True)
    return rpk, warns, took, len(entries)


def main():
    for p, what in ((CITYENGINE, "CityEngine 2026.1"), (SEVENZIP, "7-Zip")):
        if not os.path.exists(p):
            sys.exit("%s not found: %s" % (what, p))
    pal = C.load_palette(SLUG)
    text = make_rule(pal)
    rd = os.path.join(OUT, "rules"); os.makedirs(rd, exist_ok=True)
    open(os.path.join(rd, NAME + ".cga"), "w", encoding="utf-8").write(text)
    rpk, warns, took, n_entries = compile_and_pack(pal, text)
    import pyprt
    info = pyprt.get_rpk_attributes_info(rpk)
    if not info:
        sys.exit("verify FAILED: PRT read no attributes from %s" % rpk)
    res = {"rpk": os.path.relpath(rpk, C.ROOT).replace("\\", "/"), "bytes": os.path.getsize(rpk), "rule": "rules/%s.cga" % NAME,
           "built": time.strftime("%Y-%m-%dT%H:%M:%S"), "compiler": "CityEngine 2026.1 com.esri.cgac.application (headless, throw-away workspace)",
           "compile_s": round(took, 1), "resolvemap_entries": n_entries, "attributes": sorted(info), "warnings": warns,
           "pyprt": "1.12 (PRT %s)" % ".".join(str(v) for v in pyprt.get_api_version())}
    json.dump(res, open(os.path.join(OUT, "rpk_info.json"), "w", encoding="utf-8"), indent=1)
    print(json.dumps(res, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
